### ISSUE TITLE
Can I link to you on Prefect README/docs?

### ISSUE THREAD

**Issue by lauralorenz** [AndrewRook/prefect_ds#13]
Hi @AndrewRook! We want to make a place to showcase plugins outside of Prefect master branch from Prefect docs/README. Would it be ok if I link to your repo here as our guinea pig? I know parts of what you worked on are in PRs to core now, but I'm still interested in listing it as a plugin in the meantime :)

**Comment by AndrewRook** [comment]
Sure, feel free. Thanks for asking!

**Comment by lauralorenz** [comment]
@AndrewRook Awesome, thank you :)
