### ISSUE TITLE
Supserseded?

### ISSUE THREAD

**Issue by NickCrews** [AndrewRook/prefect_ds#15]
I think this library is now superseded by the prefect built in PandasSerializer? https://docs.prefect.io/api/latest/engine/serializers.html#pandasserializer

If so, maybe a small note at the top of the readme pointing people towards that might be nice, so people don't go down this offshoot path.

**Comment by AndrewRook** [comment]
Yeah, good point. I don't know about the other functionality I made in here but the serializer at least has been in Prefect for some time. Either way there have been so many changes to Prefect since I made this repo that it's probably incompatible by now.
